export const HOSTS = [
  "home",
  "n00dles",
  "foodnstuff",
  "sigma-cosmetics",
  "joesguns",
  "hong-fang-tea",
  "harakiri-sushi",
  "iron-gym",
  "darkweb",
  "frk-server-0",
  "frk-server-1",
  "frk-server-2",
  "frk-server-3",
  "frk-server-4",
  "zer0",
  "nectar-net",
  "max-hardware",
  "CSEC",
  "omega-net",
  "neo-net",
  "silver-helix",
  "phantasy",
  "the-hub",
  "crush-fitness",
  "johnson-ortho",
  "avmnite-02h",
  "computek",
  "netlink",
  "zb-institute",
  "summit-uni",
  "syscore",
  "catalyst",
  "I.I.I.I",
  "rothman-uni",
  "lexo-corp",
  "rho-construction",
  "millenium-fitness",
  "aevum-police",
  "alpha-ent",
  "global-pharm",
  "galactic-cyber",
  "aerocorp",
  "snap-fitness",
  "omnia",
  "deltaone",
  "unitalife",
  "solaris",
  "defcomm",
  "zeus-med",
  "icarus",
  "univ-energy",
  "nova-med",
  "infocomm",
  "taiyang-digital",
  "zb-def",
  "microdyne",
  "applied-energetics",
  "titan-labs",
  "run4theh111z",
  "stormtech",
  "helios",
  "vitalife",
  "fulcrumtech",
  "4sigma",
  ".",
  "omnitek",
  "kuai-gong",
  "clarkinc",
  "b-and-a",
  "powerhouse-fitness",
  "blade",
  "nwo",
  "megacorp",
  "The-Cave",
  "ecorp",
  "fulcrumassets",
];

export const SPECIAL_HOSTS = [
  { host: "CSEC", lvl: 60, ports: 1, wait: 4000 },
  { host: "avmnite-02h", lvl: 210, ports: 2, wait: 4000 },
  { host: "I.I.I.I", lvl: 365, ports: 3, wait: 4000 },
  { host: "run4theh111z", lvl: 524, ports: 4, wait: 4000 },
  { host: "powerhouse-fitness", lvl: 1078, ports: 5, wait: 165000 },
  { host: "The-Cave", lvl: 925, ports: 5, wait: 4000 },
];
