export const DISTFILES = [
  "dist/auto.js",
  "dist/share.js",
  "dist/hack.js",
  "dist/grow.js",
  "dist/weak.js",
];

export const SPECIAL_HOSTS = [
  { host: "CSEC", lvl: 60, ports: 1 },
  { host: "avmnite-02h", lvl: 220, ports: 2 },
  { host: "I.I.I.I", lvl: 346, ports: 3 },
  { host: "run4theh111z", lvl: 538, ports: 4 },
  { host: "The-Cave", lvl: 925, ports: 5 },
  { host: "powerhouse-fitness", lvl: 1031, ports: 5 },
  //{ host: 'w0r1d d43m0n', lvl: 2500, ports: 5}
];

export const DARKWEB_PROGRAMS = [
  { program: "BruteSSH.exe", price: 500000 }, 
  { program: "FTPCrack.exe", price: 1500000 }, 
  { program: "relaySMTP.exe", price: 5000000 }, 
  { program: "HTTPWorm.exe", price: 30000000 }, 
  { program: "SQLInject.exe", price: 250000000 },
];

export const C = {
  black: "\u001b[30m",
  red: "\u001b[31m",
  green: "\u001b[32m",
  yellow: "\u001b[33m",
  blue: "\u001b[34m",
  magenta: "\u001b[35m",
  cyan: "\u001b[36m",
  white: "\u001b[37m",
  brightBlack: "\u001b[30;1m",
  brightRed: "\u001b[31;1m",
  brightGreen: "\u001b[32;1m",
  brightYellow: "\u001b[33;1m",
  brightBlue: "\u001b[34;1m",
  brightMagenta: "\u001b[35;1m",
  brightCyan: "\u001b[36;1m",
  brightWhite: "\u001b[37;1m",
  reset: "\u001b[0m",
};

export const STOCK_HOST_COLLECTION = [
  { sym: "FNS", host: "foodnstuff" },
  { sym: "SYSC", host: "syscore" },
  { sym: "RHOC", host: "rho-construction" },
  { sym: "AERO", host: "aerocorp" },
  { sym: "CTK", host: "computek" },
  { sym: "LXO", host: "lexo-corp" },
  { sym: "APHE", host: "alpha-ent" },
  { sym: "GPH", host: "global-pharm" },
  { sym: "OMN", host: "omnia" },
  { sym: "UNV", host: "univ-energy" },
  { sym: "STM", host: "stormtech" },
  { sym: "NVMD", host: "nova-med" },
  { sym: "MDYN", host: "microdyne" },
  { sym: "ICRS", host: "icarus" },
  { sym: "TITN", host: "titan-labs" },
  { sym: "FLCM", host: "fulcrumassets" },
  { sym: "FSIG", host: "4sigma" },
  { sym: "VITA", host: "vitalife" },
  { sym: "SLRS", host: "solaris" },
  { sym: "HLS", host: "helios" },
  { sym: "OMTK", host: "omnitek" },
  { sym: "BLD", host: "blade" },
  { sym: "CLRK", host: "clarkinc" },
  { sym: "MGCP", host: "megacorp" },
  { sym: "KGI", host: "kuai-gong" },
  { sym: "ECP", host: "ecorp" },
  { sym: "DCOMM", host: "defcomm" },
  { sym: "SGC", host: "sigma-cosmetics" },
  { sym: "JGN", host: "joesguns" },
  { sym: "OMGA", host: "omega-net" },
  { sym: "NTLK", host: "netlink" },
  { sym: "CTYS", host: "catalyst" },
];
