export const DARKWEB_PROGRAMS = [
  { program: "BruteSSH.exe", price: 500000 },
  { program: "FTPCrack.exe", price: 1500000 },
  { program: "relaySMTP.exe", price: 5000000 },
  { program: "HTTPWorm.exe", price: 30000000 },
  { program: "SQLInject.exe", price: 250000000 },
];

export const STOCK_HOST_COLLECTION = [
  { sym: "FNS", host: "foodnstuff" },
  { sym: "SYSC", host: "syscore" },
  { sym: "RHOC", host: "rho-construction" },
  { sym: "AERO", host: "aerocorp" },
  { sym: "CTK", host: "computek" },
  { sym: "LXO", host: "lexo-corp" },
  { sym: "APHE", host: "alpha-ent" },
  { sym: "GPH", host: "global-pharm" },
  { sym: "OMN", host: "omnia" },
  { sym: "UNV", host: "univ-energy" },
  { sym: "STM", host: "stormtech" },
  { sym: "NVMD", host: "nova-med" },
  { sym: "MDYN", host: "microdyne" },
  { sym: "ICRS", host: "icarus" },
  { sym: "TITN", host: "titan-labs" },
  { sym: "FLCM", host: "fulcrumassets" },
  { sym: "FSIG", host: "4sigma" },
  { sym: "VITA", host: "vitalife" },
  { sym: "SLRS", host: "solaris" },
  { sym: "HLS", host: "helios" },
  { sym: "OMTK", host: "omnitek" },
  { sym: "BLD", host: "blade" },
  { sym: "CLRK", host: "clarkinc" },
  { sym: "MGCP", host: "megacorp" },
  { sym: "KGI", host: "kuai-gong" },
  { sym: "ECP", host: "ecorp" },
  { sym: "DCOMM", host: "defcomm" },
  { sym: "SGC", host: "sigma-cosmetics" },
  { sym: "JGN", host: "joesguns" },
  { sym: "OMGA", host: "omega-net" },
  { sym: "NTLK", host: "netlink" },
  { sym: "CTYS", host: "catalyst" },
];
