export const SPECIAL_HOSTS = [
  { host: "CSEC", lvl: 60, ports: 1, wait: 5000 },
  { host: "avmnite-02h", lvl: 220, ports: 2, wait: 5000 },
  { host: "I.I.I.I", lvl: 346, ports: 3, wait: 5000 },
  { host: "run4theh111z", lvl: 538, ports: 4, wait: 5000 },
  { host: "The-Cave", lvl: 925, ports: 5, wait: 5000 },
  { host: "powerhouse-fitness", lvl: 1031, ports: 5, wait: 15000 },
  //{ host: 'w0r1d d43m0n', lvl: 2500, ports: 5}
];

export const DARKWEB_PROGRAMS = [
  { program: "BruteSSH.exe", price: 500000 },
  { program: "FTPCrack.exe", price: 1500000 },
  { program: "relaySMTP.exe", price: 5000000 },
  { program: "HTTPWorm.exe", price: 30000000 },
  { program: "SQLInject.exe", price: 250000000 },
];

export const SERVERS = [
  "home",
  "n00dles",
  "foodnstuff",
  "sigma-cosmetics",
  "joesguns",
  "hong-fang-tea",
  "harakiri-sushi",
  "iron-gym",
  "darkweb",
  "nectar-net",
  "CSEC",
  "zer0",
  "max-hardware",
  "neo-net",
  "silver-helix",
  "omega-net",
  "phantasy",
  "the-hub",
  "netlink",
  "johnson-ortho",
  "crush-fitness",
  "computek",
  "avmnite-02h",
  "syscore",
  "summit-uni",
  "I.I.I.I",
  "rothman-uni",
  "zb-institute",
  "catalyst",
  "alpha-ent",
  "lexo-corp",
  "millenium-fitness",
  "rho-construction",
  "aevum-police",
  "galactic-cyber",
  "global-pharm",
  "snap-fitness",
  "aerocorp",
  "deltaone",
  "unitalife",
  "omnia",
  "defcomm",
  "univ-energy",
  "solaris",
  "zeus-med",
  "icarus",
  "nova-med",
  "infocomm",
  "zb-def",
  "taiyang-digital",
  "run4theh111z",
  "titan-labs",
  "microdyne",
  "applied-energetics",
  "stormtech",
  "fulcrumtech",
  "helios",
  "vitalife",
  "omnitek",
  "4sigma",
  ".",
  "kuai-gong",
  "b-and-a",
  "powerhouse-fitness",
  "nwo",
  "clarkinc",
  "blade",
  "ecorp",
  "megacorp",
  "fulcrumassets",
  "The-Cave",
  "w0r1d_d43m0n"
];

export const STOCK_HOST_COLLECTION = [
  { sym: "FNS", host: "foodnstuff" },
  { sym: "SYSC", host: "syscore" },
  { sym: "RHOC", host: "rho-construction" },
  { sym: "AERO", host: "aerocorp" },
  { sym: "CTK", host: "computek" },
  { sym: "LXO", host: "lexo-corp" },
  { sym: "APHE", host: "alpha-ent" },
  { sym: "GPH", host: "global-pharm" },
  { sym: "OMN", host: "omnia" },
  { sym: "UNV", host: "univ-energy" },
  { sym: "STM", host: "stormtech" },
  { sym: "NVMD", host: "nova-med" },
  { sym: "MDYN", host: "microdyne" },
  { sym: "ICRS", host: "icarus" },
  { sym: "TITN", host: "titan-labs" },
  { sym: "FLCM", host: "fulcrumassets" },
  { sym: "FSIG", host: "4sigma" },
  { sym: "VITA", host: "vitalife" },
  { sym: "SLRS", host: "solaris" },
  { sym: "HLS", host: "helios" },
  { sym: "OMTK", host: "omnitek" },
  { sym: "BLD", host: "blade" },
  { sym: "CLRK", host: "clarkinc" },
  { sym: "MGCP", host: "megacorp" },
  { sym: "KGI", host: "kuai-gong" },
  { sym: "ECP", host: "ecorp" },
  { sym: "DCOMM", host: "defcomm" },
  { sym: "SGC", host: "sigma-cosmetics" },
  { sym: "JGN", host: "joesguns" },
  { sym: "OMGA", host: "omega-net" },
  { sym: "NTLK", host: "netlink" },
  { sym: "CTYS", host: "catalyst" },
];
