export const DARKWEB_PROGRAMS = [
  { program: "BruteSSH.exe", price: 500000 },
  { program: "FTPCrack.exe", price: 1500000 },
  { program: "relaySMTP.exe", price: 5000000 },
  { program: "HTTPWorm.exe", price: 30000000 },
  { program: "SQLInject.exe", price: 250000000 },
];

export const STOCK_HOST_COLLECTION = [
  { sym: "FNS", host: "foodnstuff" },
  { sym: "SYSC", host: "syscore" },
  { sym: "RHOC", host: "rho-construction" },
  { sym: "AERO", host: "aerocorp" },
  { sym: "CTK", host: "computek" },
  { sym: "LXO", host: "lexo-corp" },
  { sym: "APHE", host: "alpha-ent" },
  { sym: "GPH", host: "global-pharm" },
  { sym: "OMN", host: "omnia" },
  { sym: "UNV", host: "univ-energy" },
  { sym: "STM", host: "stormtech" },
  { sym: "NVMD", host: "nova-med" },
  { sym: "MDYN", host: "microdyne" },
  { sym: "ICRS", host: "icarus" },
  { sym: "TITN", host: "titan-labs" },
  { sym: "FLCM", host: "fulcrumassets" },
  { sym: "FSIG", host: "4sigma" },
  { sym: "VITA", host: "vitalife" },
  { sym: "SLRS", host: "solaris" },
  { sym: "HLS", host: "helios" },
  { sym: "OMTK", host: "omnitek" },
  { sym: "BLD", host: "blade" },
  { sym: "CLRK", host: "clarkinc" },
  { sym: "MGCP", host: "megacorp" },
  { sym: "KGI", host: "kuai-gong" },
  { sym: "ECP", host: "ecorp" },
  { sym: "DCOMM", host: "defcomm" },
  { sym: "SGC", host: "sigma-cosmetics" },
  { sym: "JGN", host: "joesguns" },
  { sym: "OMGA", host: "omega-net" },
  { sym: "NTLK", host: "netlink" },
  { sym: "CTYS", host: "catalyst" },
];

export const TRAVELMAP = [
  {
    city: "Volhaven",
    locations: [
      "Omnia Cybersystems",
      "SysCore Securities",
      "Millenium Fitness Gym",
      "OmniTek Incorporated",
      "Hospital",
      "World Stock Exchange",
      "Helios Labs",
      "Travel Agency",
      "NWO",
      "CompuTek",
      "ZB Institute of Technology",
      "LexoCorp",
      "The Slums",
    ],
  },
  {
    city: "Sector-12",
    locations: [
      "Powerhouse Gym",
      "Icarus Microsystems",
      "Alpha Enterprises",
      "Sector-12 City Hall",
      "Iron Gym",
      "World Stock Exchange",
      "Central Intelligence Agency",
      "Hospital",
      "DeltaOne",
      "Universal Energy",
      "MegaCorp",
      "Carmichael Security",
      "Rothman University",
      "National Security Agency",
      "Blade Industries",
      "Four Sigma",
      "FoodNStuff",
      "Joe's Guns",
      "Travel Agency",
      "The Slums",
    ],
  },
  {
    city: "New Tokyo",
    locations: [
      "Arcade",
      "DefComm",
      "Travel Agency",
      "VitaLife",
      "Noodle Bar",
      "Global Pharmaceuticals",
      "Hospital",
      "World Stock Exchange",
      "The Slums",
    ],
  },
  {
    city: "Aevum",
    locations: [
      "Aevum Police Headquarters",
      "Bachman & Associates",
      "Summit University",
      "Iker Molina Casino",
      "Snap Fitness Gym",
      "Travel Agency",
      "Hospital",
      "Fulcrum Technologies",
      "ECorp",
      "AeroCorp",
      "Crush Fitness Gym",
      "NetLink Technologies",
      "Rho Construction",
      "Clarke Incorporated",
      "Watchdog Security",
      "World Stock Exchange",
      "Galactic Cybersystems",
      "The Slums",
    ],
  },
  {
    city: "Ishima",
    locations: [
      "World Stock Exchange",
      "Storm Technologies",
      "Hospital",
      "Nova Medical",
      "0x6C1",
      "Travel Agency",
      "Omega Software",
      "The Slums",
    ],
  },
  {
    city: "Chongqing",
    locations: [
      "World Stock Exchange",
      "KuaiGong International",
      "Church of the Machine God",
      "Hospital",
      "Solaris Space Systems",
      "Travel Agency",
      "The Slums",
    ],
  },
];
